version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      # trigger the unit tests here
      - echo 'Running unit tests'
      - pip install -r tests/requirements.txt --user
      - python -m pytest tests/unit -v