version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      # trigger the integration tests here
      - echo 'Running integration tests'
      - echo ${ENV_STACK_NAME}
      - echo '!!'
      - pip install -r tests/requirements.txt --user
      - AWS_SAM_STACK_NAME=${ENV_STACK_NAME} python -m pytest tests/integration -v
