name: Deploy
on: workflow_dispatch
jobs:
  run-target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: AWS build and deploy
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: sam build && cd .aws-sam/build/PinfluencerFunction && rm -fr clean-build.sh tests events env.json README.md samconfig.toml template.yaml requirements.txt
      - run: sam deploy --no-fail-on-empty-changeset --no-confirm-changeset --stack-name pinfluencer-api-staging --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1mycbpdtzxnbk --region eu-west-2 --capabilities CAPABILITY_IAM --parameter-overrides ${{ secrets.SAM_PARAMETER_OVERRIDES }}